packages:
  - afs/*
  - packages/*
  - models/*
  - memory/*
  - examples/*
  - tests/*
  - observability/*
  - docs-examples
  - blocklets/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vscode/ripgrep'
  - esbuild
  - simple-git-hooks
