packages:
  - packages/*
  - models/*
  - memory/*
  - examples/*
  - tests/*
  - observability/*
  - docs-examples

onlyBuiltDependencies:
  - '@biomejs/biome'
  - core-js
  - core-js-pure
  - esbuild
  - fast-folder-size
  - protobufjs
  - simple-git-hooks
  - sqlite3
