packages:
  - packages/*
  - packages/observability/frontend
  - examples/*
  - tests/*
  - docs-examples
onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - puppeteer
  - simple-git-hooks
  - sqlite3
