packages:
  - packages/*
  - models/*
  - memory/*
  - examples/*
  - tests/*
  - observability/*
  - docs-examples

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - protobufjs
  - simple-git-hooks
