import { DIDSpacesMemory } from '@aigne/agent-library/did-spaces-memory/index.js';
import { AIGNE, AIAgent } from '@aigne/core';
import { OpenAIChatModel as Model } from '@aigne/openai';
import dotenv from 'dotenv-flow';
import { writeFileSync } from 'fs';
import { join } from 'path';

dotenv.config({ silent: true });

const aigne = new AIGNE({
  model: new Model({
    apiKey: process.env.OPENAI_API_KEY!,
    model: 'gpt-4o-mini',
  }),
});

const agent = AIAgent.from({
  instructions: `You are a professional crypto market analyst with persistent memory powered by DID Spaces.

## Your Capabilities
- Expert in cryptocurrency market analysis and investment strategies
- Persistent memory across sessions via DID Spaces technology
- Remember user preferences, investment history, and personal details
- Provide personalized investment insights based on remembered data

## Output Requirements
- **ALWAYS** format responses in **Markdown**
- Use **code blocks** for all technical data (JSON, YAML, crypto symbols, market data)
- Use proper **headers** and **formatting** to structure responses
- Remember personal details and reference them in future conversations
- Provide personalized advice based on remembered information
- Start with personalized greetings when appropriate
- Include relevant remembered information in your analysis

Remember: Your memory persists across sessions, so build upon previous conversations!`,
  memory: new DIDSpacesMemory({
    url:
      process.env.DID_SPACES_URL ||
      'https://bbqa4abi4d7hjydb3qo5l7lyxduukztmhj3gpghkole.did.abtnet.io/app',
    auth: {
      authorization:
        process.env.DID_SPACES_AUTHORIZATION ||
        'Bearer blocklet-zGdxEzkGqKz15PGyjDg37Mq4aZXHqzKVoPtarx2Jb4VGS',
    },
  }),
  inputKey: 'message',
});

// Test DID Spaces Memory functionality
console.log('\n' + '='.repeat(50));
console.log('🧠 MEMORY TEST 1: Store User Profile');
console.log('='.repeat(50));
const result1 = await aigne.invoke(agent, {
  message: `Hello! I'm John Doe, a doctor who likes to invest in Bitcoin. I have moderate risk tolerance and 3+ years experience.`,
});
console.log('\n' + result1.message);

console.log('\n' + '='.repeat(50));
console.log('🔍 MEMORY TEST 2: Recall Preferences');
console.log('='.repeat(50));
const result2 = await aigne.invoke(agent, {
  message: `What's my favorite cryptocurrency and why is it suitable for me?`,
});
console.log('\n' + result2.message);

console.log('\n' + '='.repeat(50));
console.log('📊 MEMORY TEST 3: Personalized Analysis');
console.log('='.repeat(50));
const result3 = await aigne.invoke(agent, {
  message: `Create a personalized investment portfolio for me based on what you remember.`,
});
console.log('\n' + result3.message);

console.log('\n' + '='.repeat(50));
console.log('✅ ALL MEMORY TESTS COMPLETED');
console.log('='.repeat(50));

// Save all results to a markdown file
const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
const filename = `memory-did-spaces-results-${timestamp}.md`;
const markdownContent = `# Memory DID Spaces Test Results

Generated on: ${new Date().toLocaleString()}

## 🧠 Memory Test 1: Store User Profile

${result1.message}

## 🔍 Memory Test 2: Recall Preferences

${result2.message}

## 📊 Memory Test 3: Personalized Analysis

${result3.message}

---

*This report was generated by the Memory DID Spaces example from the AIGNE Framework.*
`;

try {
  writeFileSync(join(process.cwd(), filename), markdownContent, 'utf8');
  console.log(`\n📄 Results saved to: ${filename}`);
  console.log(
    '💡 Open this file in a markdown viewer to see the formatted results!'
  );
} catch (error) {
  console.error('❌ Failed to save results to file:', error);
  console.log(
    '\n💡 Tip: Copy the output above and paste it into a markdown viewer or file to see the formatted results!'
  );
}
