import { MCPAgent } from '@aigne/core';
import { AIGNE, AIAgent } from '@aigne/core';
import { OpenAIChatModel as Model } from '@aigne/openai';
import dotenv from 'dotenv-flow';
import { writeFileSync } from 'fs';
import { join } from 'path';

dotenv.config({ silent: true });

const aigne = new AIGNE({
  model: new Model({
    apiKey: process.env.OPENAI_API_KEY!,
    model: 'gpt-4o-mini',
  }),
});

// Create MCP agent for DID Spaces
const mcpAgent = await MCPAgent.from({
  url: process.env.DID_SPACES_URL!,
  transport: 'streamableHttp',
  opts: {
    requestInit: {
      headers: {
        Authorization: process.env.DID_SPACES_AUTHORIZATION!,
      },
    },
  },
});
console.log('Available MCP Skills:', mcpAgent.skills);

// Create AI agent with MCP skills
const agent = AIAgent.from({
  instructions: `You are a professional DID Spaces assistant with access to DID Spaces through MCP.

## Your Capabilities
- Help users manage, explore, and manipulate DID Spaces data
- Access to various DID Spaces operations through MCP skills
- Knowledge of decentralized identity and data storage

## Output Requirements
- **ALWAYS** format responses in **Markdown**
- Use **code blocks** for all data (JSON, file contents, technical info)
- Use proper **headers** and **formatting** to structure responses
- Wrap all technical data in appropriate code blocks with syntax highlighting
- Be clear, structured, and provide context for data
- Maintain a helpful and professional tone

Remember: Every piece of technical information should be properly formatted in code blocks!`,
  skills: Object.values(mcpAgent.skills),
  inputKey: 'message',
});

// Test MCP DID Spaces functionality
console.log('\n' + '='.repeat(50));
console.log('🔍 MCP TEST 1: Check Metadata');
console.log('='.repeat(50));
const result1 = await aigne.invoke(agent, {
  message: `Check and display my DID Space metadata using head_space function.`,
});
console.log('\n' + result1.message);

console.log('\n' + '='.repeat(50));
console.log('📂 MCP TEST 2: List Objects');
console.log('='.repeat(50));
const result2 = await aigne.invoke(agent, {
  message: `List all objects in the root folder of my DID Space.`,
});
console.log(`\n${result2.message}`);

console.log('\n' + '='.repeat(50));
console.log('✏️ MCP TEST 3: Write File');
console.log('='.repeat(50));
const result3 = await aigne.invoke(agent, {
  message: `Write a test file named "test.txt" with content "Hello from MCP test - ${new Date().toISOString()}" to root directory.`,
});
console.log('\n' + result3.message);

console.log('\n' + '='.repeat(50));
console.log('✅ ALL TESTS COMPLETED');
console.log('='.repeat(50));

// Save all results to a markdown file
const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
const filename = `mcp-did-spaces-results-${timestamp}.md`;
const markdownContent = `# MCP DID Spaces Test Results

Generated on: ${new Date().toLocaleString()}

## 🔍 MCP Test 1: Check Metadata

${result1.message}

## 📂 MCP Test 2: List Objects

${result2.message}

## ✏️ MCP Test 3: Write File

${result3.message}

---

*This report was generated by the MCP DID Spaces example from the AIGNE Framework.*
`;

try {
  writeFileSync(join(process.cwd(), filename), markdownContent, 'utf8');
  console.log(`\n📄 Results saved to: ${filename}`);
  console.log(
    '💡 Open this file in a markdown viewer to see the formatted results!'
  );
} catch (error) {
  console.error('❌ Failed to save results to file:', error);
  console.log(
    '\n💡 Tip: Copy the output above and paste it into a markdown viewer or file to see the formatted results!'
  );
}
