name: Release Blocklet

env:
  NODE_OPTIONS: '--max_old_space_size=6144'

on:
  push:
    branches:
      - main

jobs:
  blocklet:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Blocklet workflow
        if: "! contains(toJSON(github.event.commits.*.message), '[skip blocklet]')"
        env:
          COMPONENT_STORE_URL: ${{ secrets.STORE_ENDPOINT_PROD }}
        uses: blocklet/action-workflow@v1
        with:
          deps-server-version: beta
          skip-deps: false
          skip-upload: false
          skip-deploy: true
          skip-release: true
          working-directory: blocklets/observability
          bundle-command: pnpm bundle
          store-endpoint: ${{ secrets.STORE_ENDPOINT_PROD }}
          store-access-token: ${{ secrets.STORE_ACCESS_TOKEN_PROD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
