name: Test Node.js

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.check.outputs.released }}
    steps:
      - name: Download release-created artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: release-created
          workflow: Release
          path: ./artifacts

      - name: Check artifact
        id: check
        run: |
          if [ -f ./artifacts/release-created.txt ]; then
            echo "released=true" >> $GITHUB_OUTPUT
          else
            echo "released=false" >> $GITHUB_OUTPUT
          fi

  test-nodejs:
    needs: check-release
    if: needs.check-release.outputs.released == 'true'

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20, 22, 23, 24]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Run Node.js tests
        working-directory: tests/nodejs
        run: npm run test
