name: Test Node.js

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approval-gate:
    if: github.event.pull_request.head.ref == 'release-please--branches--main'
    environment: release-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approval received."

  test-nodejs:
    needs: approval-gate

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ["20.0", "22.0", "23.0", "24.0", "24"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Fix Node 22 Windows npm issue
        if: matrix.os == 'windows-latest' && matrix.node-version == '22.0'
        run: |
          corepack enable
          corepack prepare npm@latest --activate

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm install

      - name: Build project
        # @aigne/test-browser deps vite that is not support node 20.0, skip it
        run: |
          pnpm --filter='!test-browser' build
          # Make sure aigne cli is linked to node_modules/.bin/aigne
          pnpm install

      - name: Run Node.js tests
        working-directory: tests/nodejs
        run: pnpm test

      - name: Run Node.js (commonjs) tests
        working-directory: tests/nodejs-cjs
        run: pnpm test
